### ISSUE TITLE
Repo overhaul with AutoML template

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#117]
With the AutoML template repo finished, we could integrate DACBench into the new standard. This would extend the precommits and transfer the documentation.

**Comment by eddiebergman** [comment]
This would be hard to do as the template will only work from scratch. You can generate the template yourself locally and see what files are generated and copy them over, otherwise I can take a look at doing so :)

**Comment by TheEimer** [comment]
Something like that was my plan, let's see how it goes :D

**Comment by renesass** [comment]
Or just do it on another branch and merge it :)
