### ISSUE TITLE
Feature Request: migrate from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [automl/DACBench#130]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by TheEimer** [comment]
Sure, I'll keep you updated here

**Comment by TheEimer** [comment]
The migration is complete now and everything works with gymnasium, so you can update now :D

**Comment by elliottower** [comment]
> The migration is complete now and everything works with gymnasium, so you can update now :D

Great to hear, thanks! Any chance you could bump the version to the newest 028.1? You’re currently using 0.26.3 which has a few bugs which have been fixed since. Sorry to bug you but figure might as well keep things up to date and ensure future compatibility and such.

**Comment by TheEimer** [comment]
The problem is that ray is in the examples and the RLlib still uses 0.26.3 for now. I relaxed the version, though, so unless examples are specified, 0.28.1 should be used.
