### ISSUE TITLE
Complete test coverage

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#14]
A few lines are missing here and there and the baselines have no tests yet, this should change.

**Comment by maximilianreimer** [comment]
While started implementing a couple of additional tests I stumble upon the following things I did not understand and therefore I added no tests here:

    In dacbench.abstract_benchmark.AbstractBenchmark.save_config and dacbench.abstract_benchmark.AbstractBenchmark.read_config_file are using field
        observation_space
        action_space
        but I couldn't find a single config file using those fields, are they still in use?

    The read_configmethods has a way of handling the case where observation_space_type": "None" the saving methods not (requires at least observation_space_args to be in config). What is the expected behaviour?

    The functions in dacbench/challenge_benchmarks/reward_quality_challenge/reward_functions.py as if they should be inside of a class but they aren't.

    Same as 3. but fore dacbench/challenge_benchmarks/state_space_challenge/random_states.py

**Comment by maximilianreimer** [comment]
In general, what is the threshold we want to achieve?

**Comment by maximilianreimer** [comment]
* [ ] `dacbench/envs/rl-plan/` remove from coverage report
 * [ ] `run_baselines`
 * [ ]  ... 
 * 90% target
