### ISSUE TITLE
Lazy imports for examples?

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#20]
The examples use many different dependencies, maybe lazy imports would be a possibility to reduce the overhead and only use what's installed.

**Comment by maximilianreimer** [comment]
I am not sure if really get what the idea is here: Am I right that lazy loading means that you don't check at module level if an imported package exits but at the first usage? 

The aim is here to reduce the number of packages the user has to install if she/he wants only to run a specific example, right? 

If that's the case this has only influence on examples that use overlapping files which are importing modules that just one needs. Could we not just split those us into separate files? And add an extra for each benchmark examples separately? 

Benchmark examples: 
| File | Dependencies | 
| :--- | :--- | 
| baselines_ppo_sigmoid.py | stable_baselines, tensorflow |
| chainerrl_cma.py |  examples.example_utils -> (chainer, chainerrl) |
| ray_dqn_fd.py |  ray |
| tabular_luby.py |  examples.example_utils.q_learning -> (chainer, chainerrl) |

For `tabular_luby.py` the dependencies could easily remove by moving the required function into a separate utils file.

**Comment by TheEimer** [comment]
This was André's suggestion and the idea was to be able to run e.g. CMA even if chainer is not installed if ray is. But I'm not sure if that's necessary or even makes that much sense in examples. Your suggestion of spliting utils is smart, though!

**Comment by maximilianreimer** [comment]
Did the seperation in 689ef06cbbef187419b5030bf8d1674f031200ab

Should look deeper into this or close this issue?
