### ISSUE TITLE
Improve Seeding (Envs)

### ISSUE THREAD

**Issue by maximilianreimer** [automl/DACBench#30]
There are currently two issues with seeding: 

- [x] Seeds are not stored in env. This could facilitate logging. Fix: copy from config and set in `seed(...)`
- [x] Seeds are not set for action and observation spaces. This leads for example to undetermined action sequences of the RandomAgent. Fix: set in constructor and in `seed(...)`

**Comment by maximilianreimer** [comment]
Don't set the seed of spaces by default (according to @TheEimer ). Only optional.

**Comment by TheEimer** [comment]
TODO: replace usage of seed with the seed method and self.np_random instead of using the given seed directly

**Comment by maximilianreimer** [comment]
There a few things to discuss here: 
1. Should we even set the global numpy seed random (`np.random.seed(seed)`) or should encourage the usage of the environment-specific random number generator as recommended (e.g. [here](https://github.com/openai/gym/issues/91))? (`self.np_random, seed = seeding.np_random(seed)`) 
2. Currently the seed used to seed the global numpy random generator is **not** the one return by `gym.util.seeding.np_random(seed)` (due to this [issue](https://github.com/openai/gym/issues/2210)) this could related in correlated behaviour of correlated seed. (For more info seed [here](https://github.com/openai/gym/blob/151ba406ebf07c5274c99542549aaacd6f70ba24/gym/utils/seeding.py#L20)) 
3. To 2. add to guidelines?

**Comment by maximilianreimer** [comment]
Add seeding for action spaces to config

**Comment by maximilianreimer** [comment]
`FDEnvSelHeur`  in `dacbench/envs/rl-plan/rl-env/fd_env.py`  is not a implementation of AbastractEnv. Should we refractor it or just keep it that way, using its own seeding mechanism?

**Comment by maximilianreimer** [comment]
Add to contribution guide is related to #65
