### ISSUE TITLE
Undertemined Behavior of Modea

### ISSUE THREAD

**Issue by maximilianreimer** [automl/DACBench#32]
While writing [a test](https://github.com/automl/DACBench/blob/2c032852194a7fe1e68d93e22e5cbb9ccdec7a04/tests/wrappers/test_action_tracking_wrapper.py#L23) for the logging of action spaces I discovered that Modea does not seem to be perfectly deterministic.

The number of steps performed before done with the episode is in roughly one of 10 cases not 10 but 11.

That is the reason for [this line](https://github.com/automl/DACBench/blob/2c032852194a7fe1e68d93e22e5cbb9ccdec7a04/tests/wrappers/test_action_tracking_wrapper.py#L200)

**Comment by TheEimer** [comment]
This will be replaced, so this is not a priority

**Comment by TheEimer** [comment]
The modea package is now completely removed, so removing this.
