### ISSUE TITLE
CMA-ES Windows Compatibility

### ISSUE THREAD

**Issue by Steven-Adriaensen** [automl/DACBench#47]
Some import in the cma-es environment currently fails on windows.
Fix: Only import benchmarks that the user wants to use?

**Comment by Steven-Adriaensen** [comment]
It turns out that this failure also occurs on other OS (resource limit call fails)

**Comment by Steven-Adriaensen** [comment]
Things to try / possible solutions:

At install time:
- check whether adding resource can cause failure on windows / mac
- check whether we can store what benchmarks are installed for later use at runtime to do conditional important

At runtime, in init.py 
- ideally, only import environments that are belonging to benchmarks that are installed
- alternatively, import all benchmarks, but catch import errors to produce warnings that a certain benchmark is not installed (rather than failing)

**Comment by TheEimer** [comment]
CMA-ES can be installed separately or run in a container, closing this issue since Windows won't be a priority OS.
