### ISSUE TITLE
Add contribution guide in docs

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#65]

**Comment by maximilianreimer** [comment]
Not sure if the right place ( @TheEimer what do you think), but somewhere should be mentioned: 
* how to run the tests
* how to run coverage
* use flake and black (pre-commit hook is automatically in use if `dev` extra is  installed, is it?)
* how to build docs locally 
* structure of the repo

**Comment by TheEimer** [comment]
I think that would be exactly the right place to mention stuff like this (and also that it's important to test locally because we so automatically after pushing). Thanks for the ideas!

**Comment by TheEimer** [comment]
Add seeding: use numpy generators instead of np.random

**Comment by TheEimer** [comment]
We now have a contribution guide with the info mentioned here
