### ISSUE TITLE
Autobuild docs

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#66]
This could be done through GitHub actions

**Comment by maximilianreimer** [comment]
Updated the build process to the currently recommended way and version 2. No need for additional requirements.txt anymore.

**Comment by maximilianreimer** [comment]
The build process is triggered via webhook on readthedocs if something is committed to main. @TheEimer should I close this issue?

**Comment by TheEimer** [comment]
Sounds like it, thanks! :D
