### ISSUE TITLE
Tests are failing 

### ISSUE THREAD

**Issue by maximilianreimer** [automl/DACBench#69]
Some tests are currently failing. Locally on my machine as well as on the gi CI. 

There are two kinds of reasons for test failures: 
1. The MNIST Data is not available (any more?). This causes the tests `TestSGDEnv::test_get_default_state`, `est_sgd.py::TestSGDEnv::test_reset ` and `TestSGDEnv::test_step`to fail.

```
HTTP Error 503: Service Unavailable

/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/urllib/request.py:650: HTTPError
----------------------------- Captured stdout call -----------------------------
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
```
2. The other test that is failing is the fast-downward benchmark, where a time out is received from local server.
```
...
self = <socket.socket fd=15, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('0.0.0.0', 54412)>

    def accept(self):
        """accept() -> (socket object, address info)
    
        Wait for an incoming connection.  Return a new socket
        representing the connection, and the address of the client.
        For IP sockets, the address info is a pair (hostaddr, port).
        """
>       fd, addr = self._accept()
E       socket.timeout: timed out

/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/socket.py:205: timeout
```

For more details see [the CI Run](https://github.com/automl/DACBench/actions/runs/646800329) and the corresponding [test-report](https://github.com/automl/DACBench/suites/2245341816/artifacts/46646112)

**Comment by maximilianreimer** [comment]
@TheEimer any ideas why 2. is happening?

**Comment by maximilianreimer** [comment]
I reckon 1. is just a temporary issue.

**Comment by TheEimer** [comment]
None at all, especially since it works for me locally. Probably an issue installing fd? Do you know if that's done properly here (pulling the submodule and the running install in that folder)? That's my only idea so far. It's unfortunately pretty hard to debug the port communication setup...

**Comment by maximilianreimer** [comment]
Yea, I am pretty sure, that that is not the issue. At least I am doing those two steps

**Comment by TheEimer** [comment]
I was already afraid of that... As it only happens in the scenario tests, though, there is another possibility of the ports overlapping after one test has finished. There could also be a mistake in the scenarios, I'll double check.

**Comment by TheEimer** [comment]
I think I found the mistake, the absolute fd path in the scenarios refers to my home dir... so I'll fix that and also the onell error.

**Comment by TheEimer** [comment]
It seems like the absolute path wasn't the issue after all, so maybe it's the port overlap. I'll change what is tested here then, because we want to test the loading here, no tthe integrity of the configs anyway.
Also the cloudflare protection is still a problem, I'll try another workabround I found, but apparently it could cause actual problems with sgd

**Comment by TheEimer** [comment]
I propose to close this because everything but this has been resolved: https://github.com/automl/DACBench/issues/63
Objections?
