### ISSUE TITLE
Seperate Contribution Guide for Benchmarks

### ISSUE THREAD

**Issue by maximilianreimer** [automl/DACBench#75]
Maybe it would be a good idea to have a separate or at least more detailed description of the steps to do and things to take care of.

**Comment by maximilianreimer** [comment]
There is already a md file `dacbench/benchmarks/add_new_benchmark.md`. Should at least be mentioned

**Comment by TheEimer** [comment]
I'm still not sure if we want to do that or tell them to contact us if they want to add a benchmark, I'd like to talk about that before I add the .md file to the contrib guide
