### ISSUE TITLE
Make spaces more AC-like

### ISSUE THREAD

**Issue by TheEimer** [automl/DACBench#80]
For the user, we should probably treat our action space less like an RL problem, but more like a more traditional AC search space

**Comment by maximilianreimer** [comment]
### Implementation Plan: 
create a class that inherits from `ConfigSpace.ConfigurationSpace` but also provides (almost) the gym.Space interface.  For an implementation draft see branch [`config_space_draft`](https://github.com/automl/DACBench/tree/config_space_draft).

**Comment by TheEimer** [comment]
I did a very course version that just converts configspaces into gym spaces. We should implement this draft for different action space option, though!

**Comment by eddiebergman** [comment]
Hi @TheEimer, would it make sense to have it as part of ConfigSpace?

**Comment by TheEimer** [comment]
I mean, that would be really nice from my point of view, so if that's not too specific to have in ConfigSpace? I certainly would help us avoid issues that come with potential ConfigSpace updates

**Comment by eddiebergman** [comment]
Looking at the commit of that branch, it seems like it's just a wrapper interface around a `ConfigSpace` to be compatible with `gym.Space`?

@mfeurer , it seems like a simple wrapper and seeing as the `gym` based environment things are quite popular in RL, it could encourage RL users to use `ConfigSpace`? Perhaps part of a hackathon on ConfigSpace?
